# Go native leaf node with WebSocket listener for benchmarks.
# Connects to the hub leafnode port.
# TCP clients on 4225, WebSocket clients on 4226.
listen: 127.0.0.1:4225
leafnodes {
  remotes = [ { url: "leaf://127.0.0.1:7422" } ]
}
websocket {
  listen: "127.0.0.1:4226"
  no_tls: true
}
